import type { Property } from "@/lib/types";

export const mockProperties: Property[] = [
  {
    id: "mock-1",
    owner_id: "owner-1",
    title: "Modern 2-Bed in Lekki Phase 1",
    description:
      "Bright 2-bedroom apartment with inverter, balcony, and dedicated parking. Ideal for young professionals seeking quick access to VI and Ikoyi.",
    city: "Lagos",
    neighbourhood: "Lekki Phase 1",
    address: "Freedom Way, Lekki Phase 1",
    latitude: 6.459964,
    longitude: 3.601521,
    rental_type: "long_term",
    price: 450000,
    currency: "NGN",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    amenities: ["wifi", "parking", "security", "inverter"],
    available_from: "2025-01-05",
    max_guests: null,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-1",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "mock-2",
    owner_id: "owner-2",
    title: "Furnished Short-Let Studio in Nairobi",
    description:
      "Airy studio in Kilimani with high-speed internet, weekly cleaning, and self check-in. Perfect for remote workers and quick stays.",
    city: "Nairobi",
    neighbourhood: "Kilimani",
    address: "Lenana Rd, Kilimani",
    latitude: -1.292066,
    longitude: 36.821945,
    rental_type: "short_let",
    price: 55,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    amenities: ["wifi", "parking", "security", "cleaning"],
    available_from: "2024-12-15",
    max_guests: 2,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-2",
        image_url:
          "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "mock-3",
    owner_id: "owner-3",
    title: "3-Bed Family Home in Accra (East Legon)",
    description:
      "Spacious 3-bed with garden, fitted kitchen, and 2-car parking. Close to schools and shopping at A&C Mall.",
    city: "Accra",
    neighbourhood: "East Legon",
    address: "Adjiringanor Rd, East Legon",
    latitude: 5.631965,
    longitude: -0.174286,
    rental_type: "long_term",
    price: 1200,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    furnished: false,
    amenities: ["parking", "garden", "security"],
    available_from: "2025-02-01",
    max_guests: null,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-3",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "mock-4",
    owner_id: "owner-4",
    title: "Stylish Loft in Sandton",
    description:
      "Light-filled loft with floor-to-ceiling windows, fast Wi-Fi, inverter, and secure parking. Walkable to Sandton City and the Gautrain.",
    city: "Johannesburg",
    neighbourhood: "Sandton",
    address: "Maude St, Sandton",
    latitude: -26.1076,
    longitude: 28.0567,
    rental_type: "short_let",
    price: 80,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    amenities: ["wifi", "parking", "security", "inverter", "workspace"],
    available_from: "2025-01-10",
    max_guests: 2,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-4",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80",
      },
    ],
  },
  {
    id: "mock-5",
    owner_id: "owner-5",
    title: "Kigali Kiyovu 2-Bed with City Views",
    description:
      "Quiet 2-bed with balcony views of Kigali, backup power, and high-speed fibre. Ideal for remote workers and families.",
    city: "Kigali",
    neighbourhood: "Kiyovu",
    address: "KN 41 St, Kiyovu",
    latitude: -1.9516,
    longitude: 30.0595,
    rental_type: "long_term",
    price: 900,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    amenities: ["wifi", "parking", "security", "balcony", "backup power"],
    available_from: "2025-01-20",
    max_guests: 4,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-5",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80",
      },
    ],
  },
  {
    id: "mock-6",
    owner_id: "owner-6",
    title: "Kololo Serviced 1-Bed",
    description:
      "Serviced apartment in Kololo with daily cleaning, Wi-Fi, gym access, and 24/7 security. Minutes to Acacia Mall.",
    city: "Kampala",
    neighbourhood: "Kololo",
    address: "Upper Kololo Terrace",
    latitude: 0.335,
    longitude: 32.593,
    rental_type: "short_let",
    price: 70,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    amenities: ["wifi", "security", "cleaning", "gym", "parking"],
    available_from: "2025-01-12",
    max_guests: 2,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-6",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80",
      },
    ],
  },
  {
    id: "mock-7",
    owner_id: "owner-7",
    title: "Zamalek Riverside 2-Bed",
    description:
      "Bright Zamalek flat with Nile-side walks, fast internet, elevator access, and modern kitchen. Great for long stays.",
    city: "Cairo",
    neighbourhood: "Zamalek",
    address: "26th of July Corridor, Zamalek",
    latitude: 30.0626,
    longitude: 31.2195,
    rental_type: "long_term",
    price: 18000,
    currency: "EGP",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    amenities: ["wifi", "elevator", "security", "balcony", "parking"],
    available_from: "2025-02-05",
    max_guests: 4,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-7",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1500&q=80",
      },
    ],
  },
  {
    id: "mock-8",
    owner_id: "owner-8",
    title: "Almadies 4-Bed Villa with Pool",
    description:
      "Luxury villa in Almadies with private pool, garden, generator, and staff quarters. Close to embassies and seaside restaurants.",
    city: "Dakar",
    neighbourhood: "Almadies",
    address: "Route des Almadies",
    latitude: 14.722,
    longitude: -17.492,
    rental_type: "long_term",
    price: 2200,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 4,
    furnished: true,
    amenities: ["pool", "garden", "parking", "security", "generator"],
    available_from: "2025-02-15",
    max_guests: 8,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-8",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80",
      },
    ],
  },
  {
    id: "mock-9",
    owner_id: "owner-9",
    title: "Cocody Short-Let 2-Bed",
    description:
      "Contemporary apartment in Cocody with weekly cleaning, parking, and balcony views. Self check-in and inverter included.",
    city: "Abidjan",
    neighbourhood: "Cocody",
    address: "Boulevard Latrille, Cocody",
    latitude: 5.3575,
    longitude: -3.9519,
    rental_type: "short_let",
    price: 110,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    amenities: ["wifi", "parking", "cleaning", "inverter", "balcony"],
    available_from: "2025-01-08",
    max_guests: 4,
    is_approved: true,
    is_active: true,
    images: [
      {
        id: "img-9",
        image_url:
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1500&q=80",
      },
    ],
  },
];
