import type {
  DiscoveryIntent,
  DiscoveryKind,
  DiscoveryMarket,
  DiscoverySurface,
} from "@/lib/discovery/market-taxonomy";

export type DiscoveryCatalogueItem = {
  id: string;
  title: string;
  subtitle?: string;
  kind: DiscoveryKind;
  intent: DiscoveryIntent;
  marketTags: DiscoveryMarket[];
  params: Record<string, string>;
  priority: number;
  surfaces: DiscoverySurface[];
  disabled?: boolean;
  validFrom?: string;
  validTo?: string;
};

const ALL_SURFACES: DiscoverySurface[] = [
  "HOME_FEATURED",
  "SHORTLETS_FEATURED",
  "PROPERTIES_FEATURED",
];

export const DISCOVERY_CATALOGUE: ReadonlyArray<DiscoveryCatalogueItem> = [
  {
    id: "global-shortlet-flexible-city-breaks",
    title: "Flexible shortlets for city breaks",
    subtitle: "Fast, reliable stays for business and weekends.",
    kind: "shortlet",
    intent: "shortlet",
    marketTags: ["GLOBAL"],
    params: { guests: "2", sort: "recommended" },
    priority: 80,
    surfaces: ALL_SURFACES,
  },
  {
    id: "global-rent-family-ready-homes",
    title: "Family-ready rentals",
    subtitle: "Comfortable homes with practical amenities.",
    kind: "property",
    intent: "rent",
    marketTags: ["GLOBAL"],
    params: { category: "rent", intent: "rent" },
    priority: 76,
    surfaces: ALL_SURFACES,
  },
  {
    id: "global-buy-verified-homes",
    title: "Verified homes to buy",
    subtitle: "Trust-first listings with clear status.",
    kind: "property",
    intent: "buy",
    marketTags: ["GLOBAL"],
    params: { category: "buy", intent: "buy" },
    priority: 74,
    surfaces: ALL_SURFACES,
  },
  {
    id: "global-offplan-opportunities",
    title: "Off-plan opportunities",
    subtitle: "Long-horizon projects worth tracking.",
    kind: "property",
    intent: "buy",
    marketTags: ["GLOBAL"],
    params: { category: "off_plan", intent: "off_plan", listingIntent: "off_plan" },
    priority: 72,
    surfaces: ALL_SURFACES,
  },
  {
    id: "global-all-homes-discovery",
    title: "All homes discovery",
    subtitle: "Browse broadly before narrowing your shortlist.",
    kind: "property",
    intent: "rent",
    marketTags: ["GLOBAL"],
    params: { category: "all", intent: "all" },
    priority: 70,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ng-shortlet-lagos-weekend",
    title: "Weekend shortlets in Lagos",
    subtitle: "Curated stays for fast city breaks.",
    kind: "shortlet",
    intent: "shortlet",
    marketTags: ["NG"],
    params: { where: "Lagos", guests: "2", sort: "recommended" },
    priority: 90,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ng-rent-abuja-family",
    title: "Family rentals in Abuja",
    subtitle: "Space-first homes in central districts.",
    kind: "property",
    intent: "rent",
    marketTags: ["NG"],
    params: { category: "rent", intent: "rent", city: "Abuja" },
    priority: 88,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ng-buy-lagos-verified",
    title: "Buy verified homes in Lagos",
    subtitle: "Ready-to-view listings with clear status.",
    kind: "property",
    intent: "buy",
    marketTags: ["NG"],
    params: { category: "buy", intent: "buy", city: "Lagos" },
    priority: 86,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ng-offplan-abuja-growth",
    title: "Off-plan picks in Abuja",
    subtitle: "Projects with long-horizon upside.",
    kind: "property",
    intent: "buy",
    marketTags: ["NG"],
    params: { category: "off_plan", intent: "off_plan", listingIntent: "off_plan", city: "Abuja" },
    priority: 84,
    surfaces: ALL_SURFACES,
  },
  {
    id: "uk-shortlet-london-central",
    title: "Central shortlets in London",
    subtitle: "Reliable options for quick city stays.",
    kind: "shortlet",
    intent: "shortlet",
    marketTags: ["UK"],
    params: { where: "London", guests: "2", sort: "recommended" },
    priority: 90,
    surfaces: ALL_SURFACES,
  },
  {
    id: "uk-rent-manchester-family",
    title: "Family rentals in Manchester",
    subtitle: "Neighbourhood homes with balanced commute access.",
    kind: "property",
    intent: "rent",
    marketTags: ["UK"],
    params: { category: "rent", intent: "rent", city: "Manchester" },
    priority: 88,
    surfaces: ALL_SURFACES,
  },
  {
    id: "uk-buy-birmingham-verified",
    title: "Buy verified homes in Birmingham",
    subtitle: "Trust-first listings with clear details.",
    kind: "property",
    intent: "buy",
    marketTags: ["UK"],
    params: { category: "buy", intent: "buy", city: "Birmingham" },
    priority: 86,
    surfaces: ALL_SURFACES,
  },
  {
    id: "uk-offplan-leeds-growth",
    title: "Off-plan options in Leeds",
    subtitle: "Growth-focused inventory for long-term plans.",
    kind: "property",
    intent: "buy",
    marketTags: ["UK"],
    params: { category: "off_plan", intent: "off_plan", listingIntent: "off_plan", city: "Leeds" },
    priority: 84,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ca-shortlet-toronto-downtown",
    title: "Downtown shortlets in Toronto",
    subtitle: "One-tap stays for business and weekend trips.",
    kind: "shortlet",
    intent: "shortlet",
    marketTags: ["CA"],
    params: { where: "Toronto", guests: "2", sort: "recommended" },
    priority: 90,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ca-rent-vancouver-family",
    title: "Family rentals in Vancouver",
    subtitle: "Comfortable homes near key transit corridors.",
    kind: "property",
    intent: "rent",
    marketTags: ["CA"],
    params: { category: "rent", intent: "rent", city: "Vancouver" },
    priority: 88,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ca-buy-calgary-verified",
    title: "Buy verified homes in Calgary",
    subtitle: "High-confidence listings with transparent status.",
    kind: "property",
    intent: "buy",
    marketTags: ["CA"],
    params: { category: "buy", intent: "buy", city: "Calgary" },
    priority: 86,
    surfaces: ALL_SURFACES,
  },
  {
    id: "ca-offplan-montreal-growth",
    title: "Off-plan projects in Montreal",
    subtitle: "New-build opportunities with long-term upside.",
    kind: "property",
    intent: "buy",
    marketTags: ["CA"],
    params: { category: "off_plan", intent: "off_plan", listingIntent: "off_plan", city: "Montreal" },
    priority: 84,
    surfaces: ALL_SURFACES,
  },
  {
    id: "us-shortlet-nyc-central",
    title: "Central shortlets in New York",
    subtitle: "Fast options for short work and leisure trips.",
    kind: "shortlet",
    intent: "shortlet",
    marketTags: ["US"],
    params: { where: "New York", guests: "2", sort: "recommended" },
    priority: 90,
    surfaces: ALL_SURFACES,
  },
  {
    id: "us-rent-austin-family",
    title: "Family rentals in Austin",
    subtitle: "Flexible layouts in well-connected areas.",
    kind: "property",
    intent: "rent",
    marketTags: ["US"],
    params: { category: "rent", intent: "rent", city: "Austin" },
    priority: 88,
    surfaces: ALL_SURFACES,
  },
  {
    id: "us-buy-seattle-verified",
    title: "Buy verified homes in Seattle",
    subtitle: "Clear listing quality and trust markers.",
    kind: "property",
    intent: "buy",
    marketTags: ["US"],
    params: { category: "buy", intent: "buy", city: "Seattle" },
    priority: 86,
    surfaces: ALL_SURFACES,
  },
  {
    id: "us-offplan-miami-growth",
    title: "Off-plan options in Miami",
    subtitle: "New inventory for long-term planning.",
    kind: "property",
    intent: "buy",
    marketTags: ["US"],
    params: { category: "off_plan", intent: "off_plan", listingIntent: "off_plan", city: "Miami" },
    priority: 84,
    surfaces: ALL_SURFACES,
  },
];
