export type PlaceSeedEntry = {
  placeId: string;
  label: string;
  subtitle?: string;
  countryCode: string;
  marketHint?: string;
  latitude?: number;
  longitude?: number;
  bbox?: string;
  aliases?: string[];
  popularity?: number;
};

export const SHORTLET_PLACE_SEED: PlaceSeedEntry[] = [
  {
    placeId: "ng-lagos",
    label: "Lagos",
    subtitle: "Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.5244,
    longitude: 3.3792,
    bbox: "2.7,6.2,4.3,6.8",
    aliases: ["eko"],
    popularity: 100,
  },
  {
    placeId: "ng-abuja",
    label: "Abuja",
    subtitle: "Federal Capital Territory, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 9.0765,
    longitude: 7.3986,
    bbox: "6.9,8.8,7.8,9.3",
    popularity: 98,
  },
  {
    placeId: "ng-lekki",
    label: "Lekki",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.4698,
    longitude: 3.5852,
    bbox: "3.45,6.35,3.75,6.55",
    aliases: ["lekki phase 1"],
    popularity: 96,
  },
  {
    placeId: "ng-victoria-island",
    label: "Victoria Island",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.4281,
    longitude: 3.4219,
    bbox: "3.3,6.36,3.5,6.48",
    aliases: ["vi lagos"],
    popularity: 95,
  },
  {
    placeId: "ng-ikoyi",
    label: "Ikoyi",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.4531,
    longitude: 3.4302,
    bbox: "3.35,6.39,3.48,6.5",
    popularity: 94,
  },
  {
    placeId: "ng-yaba",
    label: "Yaba",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.5152,
    longitude: 3.3677,
    bbox: "3.3,6.46,3.43,6.56",
    popularity: 92,
  },
  {
    placeId: "ng-ikeja",
    label: "Ikeja",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.6018,
    longitude: 3.3515,
    bbox: "3.25,6.52,3.45,6.68",
    popularity: 93,
  },
  {
    placeId: "ng-ajah",
    label: "Ajah",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.4651,
    longitude: 3.5656,
    bbox: "3.48,6.39,3.64,6.53",
    popularity: 87,
  },
  {
    placeId: "ng-surulere",
    label: "Surulere",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.5003,
    longitude: 3.3476,
    bbox: "3.28,6.43,3.41,6.56",
    popularity: 86,
  },
  {
    placeId: "ng-oshodi",
    label: "Oshodi",
    subtitle: "Lagos, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.5537,
    longitude: 3.3375,
    bbox: "3.26,6.5,3.4,6.6",
    popularity: 78,
  },
  {
    placeId: "ng-port-harcourt",
    label: "Port Harcourt",
    subtitle: "Rivers, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 4.8156,
    longitude: 7.0498,
    bbox: "6.8,4.65,7.2,4.95",
    popularity: 88,
  },
  {
    placeId: "ng-enugu",
    label: "Enugu",
    subtitle: "Enugu, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.5244,
    longitude: 7.5086,
    bbox: "7.33,6.4,7.67,6.62",
    popularity: 82,
  },
  {
    placeId: "ng-ibadan",
    label: "Ibadan",
    subtitle: "Oyo, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 7.3775,
    longitude: 3.947,
    bbox: "3.75,7.2,4.2,7.5",
    popularity: 84,
  },
  {
    placeId: "ng-kano",
    label: "Kano",
    subtitle: "Kano, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 12.0022,
    longitude: 8.592,
    bbox: "8.4,11.86,8.76,12.1",
    popularity: 80,
  },
  {
    placeId: "ng-kaduna",
    label: "Kaduna",
    subtitle: "Kaduna, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 10.5264,
    longitude: 7.4388,
    bbox: "7.25,10.43,7.6,10.62",
    popularity: 77,
  },
  {
    placeId: "ng-benin-city",
    label: "Benin City",
    subtitle: "Edo, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.335,
    longitude: 5.6037,
    bbox: "5.45,6.22,5.78,6.45",
    popularity: 79,
  },
  {
    placeId: "ng-jos",
    label: "Jos",
    subtitle: "Plateau, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 9.8965,
    longitude: 8.8583,
    bbox: "8.72,9.79,8.98,10",
    popularity: 70,
  },
  {
    placeId: "ng-asaba",
    label: "Asaba",
    subtitle: "Delta, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.2042,
    longitude: 6.6959,
    bbox: "6.58,6.13,6.82,6.28",
    popularity: 74,
  },
  {
    placeId: "ng-uyo",
    label: "Uyo",
    subtitle: "Akwa Ibom, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 5.038,
    longitude: 7.9128,
    bbox: "7.8,4.95,8.02,5.14",
    popularity: 69,
  },
  {
    placeId: "ng-calabar",
    label: "Calabar",
    subtitle: "Cross River, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 4.9517,
    longitude: 8.322,
    bbox: "8.2,4.87,8.43,5.03",
    popularity: 68,
  },
  {
    placeId: "ng-ijebu-ode",
    label: "Ijebu Ode",
    subtitle: "Ogun, Nigeria",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 6.8206,
    longitude: 3.9173,
    bbox: "3.79,6.72,4.04,6.92",
    popularity: 66,
  },
  {
    placeId: "ng-nigeria",
    label: "Nigeria",
    subtitle: "West Africa",
    countryCode: "NG",
    marketHint: "NG",
    latitude: 9.082,
    longitude: 8.6753,
    bbox: "2.65,4.25,14.7,13.9",
    aliases: ["naija", "ng"],
    popularity: 97,
  },
  {
    placeId: "gb-london",
    label: "London",
    subtitle: "England, United Kingdom",
    countryCode: "GB",
    marketHint: "GB",
    latitude: 51.5072,
    longitude: -0.1276,
    bbox: "-0.53,51.28,0.33,51.7",
    popularity: 90,
  },
  {
    placeId: "gb-manchester",
    label: "Manchester",
    subtitle: "England, United Kingdom",
    countryCode: "GB",
    marketHint: "GB",
    latitude: 53.4808,
    longitude: -2.2426,
    bbox: "-2.37,53.38,-2.14,53.56",
    popularity: 76,
  },
  {
    placeId: "gb-birmingham",
    label: "Birmingham",
    subtitle: "England, United Kingdom",
    countryCode: "GB",
    marketHint: "GB",
    latitude: 52.4862,
    longitude: -1.8904,
    bbox: "-2.05,52.38,-1.75,52.58",
    popularity: 73,
  },
  {
    placeId: "ke-nairobi",
    label: "Nairobi",
    subtitle: "Kenya",
    countryCode: "KE",
    marketHint: "KE",
    latitude: -1.2864,
    longitude: 36.8172,
    bbox: "36.66,-1.45,36.98,-1.16",
    popularity: 85,
  },
  {
    placeId: "ke-mombasa",
    label: "Mombasa",
    subtitle: "Kenya",
    countryCode: "KE",
    marketHint: "KE",
    latitude: -4.0435,
    longitude: 39.6682,
    bbox: "39.57,-4.14,39.76,-3.94",
    popularity: 71,
  },
  {
    placeId: "us-new-york",
    label: "New York",
    subtitle: "United States",
    countryCode: "US",
    marketHint: "US",
    latitude: 40.7128,
    longitude: -74.006,
    bbox: "-74.26,40.49,-73.7,40.92",
    popularity: 83,
  },
  {
    placeId: "us-atlanta",
    label: "Atlanta",
    subtitle: "United States",
    countryCode: "US",
    marketHint: "US",
    latitude: 33.749,
    longitude: -84.388,
    bbox: "-84.56,33.63,-84.24,33.9",
    popularity: 72,
  },
  {
    placeId: "fr-paris",
    label: "Paris",
    subtitle: "France",
    countryCode: "FR",
    latitude: 48.8566,
    longitude: 2.3522,
    bbox: "2.22,48.8,2.46,48.91",
    popularity: 81,
  },
  {
    placeId: "ae-dubai",
    label: "Dubai",
    subtitle: "United Arab Emirates",
    countryCode: "AE",
    latitude: 25.2048,
    longitude: 55.2708,
    bbox: "55.07,25.06,55.43,25.31",
    popularity: 82,
  },
  {
    placeId: "za-cape-town",
    label: "Cape Town",
    subtitle: "South Africa",
    countryCode: "ZA",
    latitude: -33.9249,
    longitude: 18.4241,
    bbox: "18.28,-34.04,18.58,-33.8",
    popularity: 75,
  },
];
