export const smokeSelectors = {
  homeVisualLanding: "home-visual-landing",
  homeFeaturedStrip: "home-featured-strip",
  homeForYouGrid: "home-for-you-grid",
  shortletsShell: "shortlets-search-shell",
  shortletsStickyPill: "shortlets-compact-search-pill",
  shortletsFiltersButton: "shortlets-filters-button",
  shortletsFiltersDrawer: "shortlets-filters-drawer",
  shortletsMapOpen: "shortlets-open-map",
  shortletsMapClose: "shortlets-map-close",
  shortletsMobileMap: "shortlets-mobile-map",
  shortletsMap: "shortlets-map",
  shortletsSearchThisArea: "shortlets-search-this-area",
  shortletsMapMoveToggle: "shortlets-map-move-toggle",
  shortletBookingWidget: "shortlet-booking-widget",
  shortletCheckInTrigger: "shortlet-checkin-trigger",
  shortletCalendarPopover: "shortlet-calendar-popover",
  shortletCalendarSheet: "shortlet-calendar-sheet",
  shortletCtaPrimary: "shortlet-cta-primary",
  shortletReturnStatus: "shortlet-return-status",
  shortletReturnFinalising: "shortlet-return-finalising",
  shortletReturnConfirmed: "shortlet-return-confirmed",
  shortletReturnPending: "shortlet-return-pending",
  hostBookingsInbox: "host-bookings-inbox",
  hostBookingRow: "host-booking-row",
  hostBookingView: "host-booking-view",
  hostBookingDrawer: "host-booking-drawer",
  hostBookingApprove: "host-booking-approve",
  hostBookingDecline: "host-booking-decline",
  hostCalendarPage: "host-calendar-page",
  hostCalendar: "host-calendar",
  hostCheckinAgenda: "host-checkin-agenda",
  hostLeadsPage: "host-leads-page",
  hostLeadsFilters: "host-leads-filters",
  hostLeadsResults: "host-leads-results",
  hostLeadsFilterStatus: "host-leads-filter-status",
  hostPropertiesPage: "host-properties-page",
  hostPropertiesManager: "host-properties-manager",
  hostPropertiesResults: "host-properties-manager-results",
  hostPropertiesFilterLive: "host-properties-filter-live",
  adminShortletsOpsRoot: "admin-shortlets-ops",
  adminShortletsOpsRefresh: "admin-shortlets-ops-refresh",
  adminShortletsOpsMetrics: "admin-shortlets-ops-metrics",
  supportWidgetButton: "support-widget-button",
  supportWidgetPanel: "support-widget-panel",
  supportWidgetInput: "support-widget-input",
  supportWidgetSend: "support-widget-send",
  supportWidgetEscalate: "support-widget-escalate",
  supportWidgetTicketSuccess: "support-widget-ticket-success",
  supportWidgetSuggestions: "support-widget-suggestions",
  adminSupportTable: "admin-support-table",
  adminSupportRow: "admin-support-row",
  adminSupportDrawer: "admin-support-drawer",
  adminSupportRefresh: "admin-support-refresh",
  adminSupportStatusFilter: "admin-support-status-filter",
} as const;

export function shortletsResultLabelText(total: number, withinMapArea: boolean): RegExp {
  if (withinMapArea) {
    return new RegExp(`${total}\\s+stays?\\s+within\\s+map\\s+area`, "i");
  }
  return new RegExp(`${total}\\s+stays?\\s+found`, "i");
}
